### ISSUE TITLE
Suggestion: More space for descriptions on character sheet

### ISSUE THREAD

**Issue by smaug18** [DrOgres/tftloop#14]
The current character sheet cuts off the texts quite quickly, especially for "Drive" but also the other items there and the relationships:

![Screenshot 2021-05-10 175257](https://user-images.githubusercontent.com/5852377/117687928-96fa0a80-b1b8-11eb-9e85-21b5bbad4dfa.jpg)

Maybe put the Notes into a seperate tab to save some room?

Also at the beginning of the Notes block there seems to be a tab stop. I am not sure if this intentional or not.

I would also simplify the fonts being used. I like the font used on the left side and for the headers. Personally I would do away with the typewriter font on the right part of the sheet and use the same font like on the left. I find the typewriter font to be not very readable.

Thank you for creating this system and keep up the good work!

**Comment by DrOgres** [comment]
Hi,

I have been meaning to do something about that line issue. I have been wanting to avoid line wrap due to the way it looks but may not have much choice really.

the indent is default for the MCE editor for paragraph blocks.  I'll see if I can override it.

at this point I kind of want to keep everything on one tab if I can manage it but will think about it.

fonts will be adjusted in an upcoming release

**Comment by DrOgres** [comment]
1.0.1 addresses the majority of this.  

note that long descriptions and the like will not have a line break on them this is a factor of html input fields used for in-line data editing of the fields and will take a lot of work to address.  That being said I did some CSS adjustments to make the lines hold more text and I think it covers 99% of all cases.

this update will be on the foundry 0.8.X branch let me know if you have any issues.
